### ISSUE TITLE
El formato del markdown está mal

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-GRADOII-DSI/rafa-daniel-pedro-dsi1516#11]
El formato de markdown no es correcto @alu0100505078, en el commit 89d8a2b y el fichero [readme.md](https://github.com/ULL-ESIT-GRADOII-DSI/rafa-daniel-pedro-dsi1516/blob/master/README.md)

**Comment by PedroRamosRguez** [comment]
@DanielRamosAcosta  @Rafaherrero  ya he cambiado estilo del [readme.md](https://github.com/ULL-ESIT-GRADOII-DSI/rafa-daniel-pedro-dsi1516/blob/master/README.md) modificado en el commit 975611d.
